django_manager/urls.py
from django.contrib import admin
from django.urls import  include , path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('buildings.urls')),
]

urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('' ,views.home, name = "home"),
	path('signup/', views.signup, name='signup'),
	path('login/', views.login_views, name='login'),
	path('dashboard/', views.dashboard_view, name= 'dashboard'),
	path('logout/', views.logout_view ,name='logout'),
	path('administration/', views.restricted_view, name="administration"),
	path('administrator/',views.site_admin, name="administrator"),
	path('add_building/', views.add_building, name='add_building'),
	path('building/<pk>/edit/', views.edit_building, name='building_edit'),
	path('building/<pk>/delete/', views.delete_building, name='building_delete'),
	path('create_intervention/', views.create_intervention, name='create_intervention'),
	path('interventions/', views.intervention_list_view, name='intervention_list'),
	path('interventions/<pk>/delete/', views.delete_intervention, name='delete_intervention'),
	path('interventions/<pk>/mark_as_done/', views.mark_as_done, name='mark_as_done'),
	path('report/', views.report_incident, name='report_incident'),
	path('report/success/', views.incident_report_success, name='incident_report_success'),
	path('incidents/', views.list_incidents, name='list_incidents'),

]

models.py
# models.py
from django.db import models
from django.forms.widgets import DateInput

class Building(models.Model):

    name = models.CharField(max_length=255)

    address = models.CharField(max_length=255)

    description = models.TextField(blank=True)
    
    class Meta:
        permissions = (

                ("can_view_building", "citoyens"),

                ("can_edit_building", "permissive_uses"),

            )


    def __str__(self):

        return self.name

class BuildingHealthStatus(models.Model):
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    health_status = models.IntegerField()  
    health_status_color = models.CharField(max_length=10) 
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.building.name} Health Status"

    



class Incident(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    date_occurred = models.DateField()
    location = models.CharField(max_length=255)
    reported_by = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Intervention(models.Model):
    intervention_type = models.CharField(max_length=255)
    intervention_date = models.DateField()
    intervention_notes = models.TextField()
    is_done = models.BooleanField(default=False)

    def __str__(self):
        return f"Intervention {self.intervention_type} on {self.intervention_date}"

templates/add_building.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Flyorex-S0l
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
    <style>
      body{
        background-color: #132e44;
     }
     /* styles.css */
    .health-status-bar {
      height: 20px;
      background-color: #ccc;
      border-radius: 10px;
      padding: 2px;
    }

    .health-status-bar-inner {
      height: 100%;
      background-color: #4CAF50; /* green color */
      border-radius: 10px;
      transition: width 0.5s ease-in-out;
    }
     </style>

  </head>
  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#"class="navbar-brand" href="#"><b><i>Buildings Management-System</i></b></a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Contact</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">About</a></li>
        </ul>
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search"  placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <a  href="{% url 'administrator' %}"type="button" class="btn btn-outline-light me-2" >administration</a>
          <a  href= "{% url 'logout' %} "type="button" class="btn btn-warning" >LogOut</a>
        </div>
      </div>
    </div>
  </header>
  <h2>
    <div class="frame" style="color: white; text-align: center;">
      <h1 class="bi bi-building" >Public Buildings - Management </h1>
    </div>
  </h2>
    <div class="container">

        {% block content %}
        <h2 style="color: blue;">Add New Building</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" style="color: white;background-color:green">Add Building</button>
            <a href="{% url 'dashboard' %}"style="color: deeppink;">go back to dashboard</a>
            <style>

              label {
        
              color: white;
        
            }
        
          </style>
        </form>

        {% endblock %}

    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Flyorex-S0l
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
    <style>
      body{
        background-color: #132e44;
     }
     .frame {
       position: absolute;
       top: 50%;
       left: 50%;
       width: null;
       height: null;
       margin-top: -200px;
       margin-left: -200px;
       border-radius: 2px;
       background: none;
       color: rgb(0, 202, 252);
     }
     
     .center {
       position: absolute;
       width: 200px;
       height: 200px;
       top: 90px;
       left: 90px;
     }
     
     .dot-1 {
       position: relative;
       z-index: 3;
       width: 300px;
       height: 300px;
       top: 155px;
       left: 155px;
       background:#132e44;
       border-radius: 50%;
       -webkit-animation-fill-mode: both;
               animation-fill-mode: both;
       -webkit-animation: jump-jump-1 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
               animation: jump-jump-1 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
     }
     
     .dot-2 {
       position: absolute;
       z-index: 2;
       width: 300px;
       height: 300px;
       top: 110px;
       left: 110px;
       background: deeppink;
       border-radius: 50%;
       -webkit-animation-fill-mode: both;
               animation-fill-mode: both;
       -webkit-animation: jump-jump-2 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
               animation: jump-jump-2 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
     }
     
     .dot-3 {
       position: absolute;
       z-index: 1;
       width: 300px;
       height: 300px;
       top: 65px;
       left: 65px;
       background: #132e44;
       border-radius: 50%;
       -webkit-animation-fill-mode: both;
               animation-fill-mode: both;
       -webkit-animation: jump-jump-3 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
               animation: jump-jump-3 2s cubic-bezier(0.21, 0.98, 0.6, 0.99) infinite alternate;
     }
     
     @-webkit-keyframes jump-jump-1 {
       0%, 70% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     
     @keyframes jump-jump-1 {
       0%, 60% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     @-webkit-keyframes jump-jump-2 {
       0%, 40% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     @keyframes jump-jump-2 {
       0%, 40% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     @-webkit-keyframes jump-jump-3 {
       0%, 10% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     @keyframes jump-jump-3 {
       0%, 10% {
         box-shadow: 2px 2px 3px 2px rgba(0, 0, 0, 0.2);
         -webkit-transform: scale(0);
                 transform: scale(0);
       }
       100% {
         box-shadow: 10px 10px 15px 0 rgba(0, 0, 0, 0.3);
         -webkit-transform: scale(1);
                 transform: scale(1);
       }
     }
     
     
    </style>

  </head>
  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#"class="navbar-brand" href="#"><b><i>Buildings Management-System</i></b></a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Contact</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">About</a></li>
        </ul>
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search"  placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <a  href="{% url 'login' %}"type="button" class="btn btn-outline-light me-2" >Login</a>
          <a  href= "{% url 'signup' %} "type="button" class="btn btn-warning" >Sign-up</a>
        </div>
      </div>
    </div>
  </header>
  <h2>
    <div class="frame"style="color: white; text-align: center;">
      <i class="bi bi-building" >Public Buildings - Management </i>
        <div class="center">    
                        <div class="dot-1" style="color:lightseagreen;">efficient solution</div>
                        <div class="dot-2" style="color:lightseagreen;">better reactivity</div>
                        <div class="dot-3" style="color:lightseagreen;">simple usage</div>
        </div>
    </div>
  </h2>
  <div>{%block content%} {%endblock%} </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

templates/base0.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Flyorex-S0l
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
    <style>
      body{
        background-color:#132e44;
     }
     </style>

  </head>
  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#"class="navbar-brand" href="#"><b><i>Buildings Management-System</i></b></a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Contact</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">About</a></li>
        </ul>
          <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
          <input type="search"  placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <a  href="{% url 'login' %}"type="button" class="btn btn-outline-light me-2" >Login</a>
          <a  href= "{% url 'signup' %} "type="button" class="btn btn-warning" >Sign-up</a>
        </div>
      </div>
    </div>
  </header>
  <h2>
    <div class="frame"style="color: white; text-align: center;">
      <i class="bi bi-building" >Public Buildings - Management </i>
    </div>
  </h2>
    <div class="container">{% block content %}{% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

templates/base1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Flyorex-S0l
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
        <style>
              body{
                background-color: #132e44;
             }
                 .status-bar {
                  height: 20px;
                  border-radius: 10px;
                  padding: 2px;
                  background-color: #ccc;
                  display: flex;
                  align-items: center;
                  position: relative;
                }

                .status-bar-inner {
                  height: 100%;
                  border-radius: 10px;
                  transition: width 0.5s ease-in-out;
                  position: absolute;
                  left: 0;
                  top: 0;
                }

                .status-bar-label {
                  margin-left: 10px;
                  font-size: 14px;
                  color: #666;
                  position: absolute;
                  left: 50%;
                  transform: translateX(-50%);
                }
        </style>
    </head>
  <body>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#"class="navbar-brand" href="#"><b><i>Buildings Management-System</i></b></a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">Contact</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">FAQs</a></li>
          <li><a href="#" class="nav-link px-2 text-secondary">About</a></li>
        </ul>
          
        <form method="get" class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
                        <input type="text" placeholder="Search buildings...">
                </form>

        <div class="text-end">
          <a  href="{% url 'administrator' %}"type="button" class="btn btn-outline-light me-2" >administration</a>
          <a  href= "{% url 'logout' %} "type="button" class="btn btn-warning" >LogOut</a>
        </div>
      </div>
    </div>
  </header>
  <h2>
    <div class="frame">
      <h1 style="color: white; text-align: center;"><i class="bi bi-building"></i>Public Buildings - Management </h1>
    </div>
  </h2>
    <div class="container">
      {%block content %} {%endblock%}
         

    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

templates/building_delete.html
{% extends "base1.html"%} 
{% block content%}
    <h1 style="color: blue;">Delete Building ?</h1>

    <form method="post">
        {% csrf_token %}
        <p style="color: crimson;">Are you sure you want to delete this building?</p>
        <button type="submit" style="color: white;background-color:red">Delete</button>
        <i><a href=" {% url 'dashboard' %}"style="color:deeppink;"> go back</a></i>

    </form>
    

{%endblock%}

templates/building_edit.html
{% extends "base1.html"%} 

{% block content %}
    <h1 style="color: blue;">Edit Building</h1>


    <form method="post">

        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" style="color: white;background-color:green;font-style: italic;">Save Changes</button>
        <i><a href=" {% url 'dashboard' %}" style="color: deeppink;font-style: italic;"> go back</a></i>
        <style>

            label {
      
            color: white;
      
          }
      
        </style>
    </form>
    

{% endblock%}

templates/dashboard.html
{%extends "base1.html"%}

{% block content %}
			{% for building in buildings %}
			  <div class="building">
			    <h2 style="color: honeydew;">Building : {{ building.name }}</h2>
			    <p style="color: lightseagreen;">Address: {{ building.address }}</p>
			    <p style="color: lightseagreen;">Description: {{ building.description }}</p>
			   {% with health_status=building.buildinghealthstatus_set.first %}
			      <div class="status-bar">
			        <div class="status-bar-inner" style="width: {{ health_status.health_status }}%; background-color: {{ health_status.health_status_color }};"></div>
			        <div class="status-bar-label" style="color: darkblue;">status-bar : {{ health_status.health_status }}%</div>
			      </div>
			    {% endwith %}
			    <ul>
						<li><a href="{% url 'building_edit' building.pk %}" style="color: blue;">Edit</a></li>
						<li><a href="{% url 'building_delete' building.pk %}" style="color: blue;">Delete</a></li>
						<li><a href="{% url 'report_incident'%}" style="color: blue;">Report an Incident</li>
					</ul>

			  </div>
			{% endfor %}
				<li><a href="{% url 'add_building' %}" style="color: deeppink; font-style: italic;">Add New Building</a></li>
				<li><a href="{% url 'list_incidents' %}" style="color: deeppink;font-style: italic;">View All Incidents</a></li>
				<li><a href="{% url 'intervention_list' %}" style="color: deeppink;font-style: italic;">View Interventions</a></li>

			{% endblock %}

templates/incident_report.html
{%extends "base1.html"%}
        {% block content %}
    <h1 style="color: lightblue;">Report an Incident</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" style="color: white; background-color: green;">Submit</button>
        <a href="{% url 'dashboard' %}" style="color: deeppink;">go back</a>
        <a href="{% url 'list_incidents' %}" style="color: deeppink;">View All Incidents</a>

        <style >
            label{
                color: white;
            }
        </style>
    </form>
{% endblock %}

templates/intervention.html
{% extends "base1.html"%} 

{% block content %}
    
<h1 style="color: blue;">Intervention Form</h1>


 <form method="post">

    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit" style="color: white;background-color:green">Submit</button>
    <a href=" {% url 'dashboard' %}"style="color:deeppink;"> go back</a> 
    <style>

        label {
  
        color: white;
  
      }
  
    </style>

</form>

{% endblock %}

templates/list_incidents.html
{%extends "base1.html"%}


{% block content %}
<h1 style="color: white;">List of Incidents</h1>
<table>
    <thead>
        <tr style="color: blue;">
               <th>Title</th>
            <th>Description</th>
            <th>Date Occurred</th>
            <th>Location</th>
            <th>Reported By</th>
            <th>Created At</th>
        </tr>
    </thead>
    <tbody style="color: lightcyan;">
        {% for incident in incidents %}
        <tr>
            <td>{{ incident.title }}</td>
            <td>{{ incident.description }}</td>
            <td>{{ incident.date_occurred }}</td>
            <td>{{ incident.location }}</td>
            <td>{{ incident.reported_by.username }}</td>
            <td>{{ incident.created_at }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="6">No incidents reported.</td>
        </tr>
        {% endfor %}
</table>
<li><a href="{% url 'create_intervention'%}" style="color: deeppink;">Make Intervention</a></li>
    <li><a href="{% url 'intervention_list' %}" style="color: deeppink;">View Interventions</a></li>
    <li><a href="{% url 'dashboard' %}" style="color: deeppink;"> go back to dashboard</a></li>

{% endblock %}


    

templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h1 style="color: blue;">Login</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"style="color: white; background-color: green;">Login</button>
    <a href="{% url 'signup' %}" style="color: deeppink ; font:bolder;">Haven't account yet? go register</a>
    <style>

      label {

      color: white;

    }

  </style>
  </form>
{% endblock %}

templates/restricted.html
<!DOCTYPE html>
<html>
<head>
    <title style="color: blue;">Restricted Page</title>
</head>
<body>
            
        <h1 align="center" style="position: absolute;color:crimson">404</h1>
        <a href="{% url 'dashboard' %}"style="color:deeppink;">go back to dashboard</a>
</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1  style="color: dodgerblue;">User Registration Form</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
   {% if error %}
      <p style="color: red">{{ error }}</p>
    {% endif %}
    <button type="submit" style="color: white; background-color:green">Register</button>
    <a href="{% url 'login' %}" style="color: deeppink;">Already registered?login instead</a> 
    <style>

      label {

      color: white;

    }

  </style> 
  </form>

{% endblock %}